Revert "Issue #3361 AttributeError: 'NoneType' object has no attribute 'parameter_type'"
This reverts commit 29a965ed0f23b44a44a086132557852bfba690a9.

Change-Id: Ib4738785e97eca4e7c2036441fdfc74b2c11507d